### PR TITLE
Add initial implementation of the Arrow token

### PR DESCRIPTION
**Pull request by BrassLion**
This changeset defines the Arrow token as a basic ERC20 token and introduces a series of basic tests and tools using the Brownie framework.

Feedback encouraged! I've made some decisions about the tooling and implementation, but happy to go with other choices if people have different ideas.

### CODE REVIEW

**Review by thomasgarrison — APPROVED** [review]

**Comment by bghughes** [comment]
Nice work @BrassLion! I'm quite late on checking this out but it seems solid to me.

I wanted to ask: do you think it is helpful to have a Truffle/JS redundancy in the repository? I typically use Truffle + Mocha to iterate and test and noticed the Brownie approach here - curious to hear what you think and happy to take offline too :)

**Comment by BrassLion** [comment]
Ah great. Thanks for checking this out @bghughes.

I chose Brownie purely because I have more experience using the framework over Truffle. Do you think it would be advantageous to switch over to Truffle?

**Comment by bghughes** [comment]
> Ah great. Thanks for checking this out @bghughes.
> 
> I chose Brownie purely because I have more experience over using the framework over Truffle. Do you think it would be advantageous to switch over to Truffle?

No problem and nice work @BrassLion! My gut tells me _it would be advantageous to switch over to Truffle or Hardhat_ depending on the project's needs. The reason for this is that a lot of tooling is built on top of these systems; for instance, [Open Zeppelin Upgrades](https://docs.openzeppelin.com/upgrades-plugins/1.x/) (should the project ever want to use something like this for plug-and-play proxy management) or [network-specific tooling](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts) (I have experience with this on Optimism and Polygon so far). Moreover, I have seen TS and things like Mocha.js used well in these systems and they build nicely on Truffle/Hardhat.

Not sure if this is enough reason to switch over, please note that I am biased given my experience with these. I'd like to also add that this is the most common approach I have personally seen in the space - _all of this to say_, I don't want to knock Brownie and it could be the move depending on project needs (cc @thomasgarrison - not sure if you have a preference or want to weigh in). Also, I am happy to initialize a Hardhat or Truffle project in the same repo in addition to the existing great work done in Brownie: they use the same contract/folder structure so I think the functionality should effectively be the same (would allow the repo to test in js and whatever framework is added too).

**Comment by BrassLion** [comment]
Interesting! You're 100% right that Truffle is the more widely used framework. At least that's what I see in my (more limited) experience.

Personally, I'm far more comfortable with Brownie, because I'm a python boy deep down. There is [support for Hardhat](https://curve.substack.com/p/april-8-2021-brownie-adding-hardhat) in Brownie, and you can write tooling that is network-specific, though I imagine plugin support is more limited. 

Whatever we go with, I think we should stick with one framework rather than keeping both Truffle and Brownie competing in the same repo. Seems far simpler and less error-prone to me.

**Comment by thomasgarrison** [comment]
I don't have a lot of experience developing contracts, so I can't weigh in with a well-informed opinion here. That being said, I'm inclined to agree with @bghughes in that we probably should switch over to Truffle.

While the V1 contracts should all be fairly simple to accomplish with either framework, I'd still rather commit to using whatever is more standard and built out. Once we start writing the logic for the rideshare protocol, things could get much more complicated and I'd rather not spend time dealing with things that Truffle would have solved. Again, I don't have the experience to back up this opinion, so I'll lean on you guys to judge whether or not this is a real concern.

**Comment by BrassLion** [comment]
I've done some research into various projects and the frameworks they use, and it looks like the modern convention is to ether use Hardhat or Brownie. Hardhat has the most adoption, with brownie in a fairly close second. Truffle seems to be becoming less popular, so I think we should either **stick with Brownie or transition to Hardhat.**

I had a go at experimenting with Hardhat, and attempted to transition, but I'm just not comfortable or familiar with it or javascript enough to move this repo over to it on my own. @bghughes, I'll need you to take the lead on this if we do want to go that way.

Personally, my speed of development is _far higher_ when using Brownie, because I'm more familiar with the language. The main benefit seems to be the Hardhat plugin system, functionality which could be replicated here in Brownie as and when it's needed.

**Pull request merged**
