### PR TITLE
Enable ERC-20 asset transfers between L1 and L2

### PR DESCRIPTION
**Pull request by GoodluckH**
Included a bridging script to support asset transfers between Ethereum
and Optimism. Configured associcated settings and packages to support
the bridging script.

To perform a bridging operation:

1. Deploy a token contract on an L1 network. Note that for testnets,
   Optimism does not support Rinkeby as there are no bridging contracts
   exist on that chain. (See [SDK](https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/utils/contracts.ts#L54-L113))
2. Update the `L1_TOKEN_ADDRESS` field in `.env`
3. Deploy an L2 token contract with `npm run deployL2TokenOptimismKovan`
4. Update the `L2_TOKEN_ADDRESS` field in `.env`
5. Run `npm run depositTokenToL2` to transfer a certain amount (defined
   in `bridgeArrowToken.js`) of tokens to L2. Similarly, transfer tokens
   from L2 back to L1 by running `npm run withdrawTokenToL1`. It will
   take a quite while, so good time to grab a coffee :)
6. Call `balanceOf` on respective chains to test if bridging was
   successful

Tests were done on [here](https://kovan.etherscan.io/address/0x98Ac3742996543E09430DeD7A360eCAC07460E63) and [here](https://kovan-optimistic.etherscan.io/address/0x67352C8FA4caA3a2d1C36F4FebC513d00Cf2aAA9).

For each contract, feel free to inspect the transaction logs to check
the correctness of bridging operations.

### CODE REVIEW

**Review by BrassLion — COMMENTED** [review]
Hmm, is this the only way to bridge tokens to and from L1 via Optimism? 

This feels particularly user unfriendly to me, and contributors should not be expected to run a script in order to get their tokens back to L1.

Am I missing an easier way to do this? 

Arbitrum, for example, appears to let you bridge transparently through their bridging interface, without having to run any scripts: https://bridge.arbitrum.io/

**Comment by GoodluckH** [comment]
Yes, there's an easy way! We can simply open a [PR](https://github.com/ethereum-optimism/ethereum-optimism.github.io#adding-a-token-to-the-list) to add our token to OP's gateway list.  

Then, we can use their GUI for bridging: https://app.optimism.io/bridge. 

But I don't have all permissions needed to open that PR. I will make a note in the Discord and we can find a time with @thomasgarrison to do that.

**Comment by BrassLion** [comment]
👍 We don't need Thomas to help on this. I can open a PR when we deploy.

**Comment by BrassLion** [comment]
In which case, if we're doing it manually, does it make sense to close this PR or do you still see value in some of the changes?

**Comment by GoodluckH** [comment]
Yes, it makes sense to close this PR since there's a GUI to use.

**Pull request closed without merging**
