### PR TITLE
Add dodoc

### PR DESCRIPTION
**Pull request by GoodluckH**
Implements the [dodoc](https://github.com/primitivefinance/primitive-dodoc) plugin to automate the process of generating `.md` documentations of smart contracts.

### CODE REVIEW

**Review by BrassLion — COMMENTED** [review]
I don't know enough about the current plans / workflows for docs to make an informed decision on this.

Tagging @owlot and @thomasgarrison who will know better about the best way to integrate this into the wider organisation docs.

**Comment by BrassLion** [comment]
dodoc also doesn't seem to be a super popular project to rely on. Is there a more established doc generator we can use?

I'd also recommend not committing the generated docs into the repository, but creating an Action that generates and publishes the docs to the appropriate places.

**Comment by GoodluckH** [comment]
There is a [solution](https://github.com/OpenZeppelin/solidity-docgen) by OpenZeppelin, but it functionally it's very similar. 

I picked dodoc based on the validation that thirdweb, a pretty large web3 project/company, uses dodoc in their [repo](https://github.com/thirdweb-dev/contracts) and uses a GitHub [Action](https://github.com/thirdweb-dev/contracts/actions/workflows/dispatch_docs.yml) to integrate generated docs to their website.

**Comment by owlot** [comment]
For the integration with Docusaurus, it doesn't really matter which tool we'll be using to generate the docs. As long as it outputs Markdown files, we're good.
I agree that we don't want to push the generated docs to GitHub though, just like you won't push your compiled binaries. I can add an action to the pipeline to trigger the docs generation and push the files to Docusaurus.

**Review by owlot — COMMENTED** [review]
I've removed the generated docs and instead added a workflow to generate and push the docs to S3

**Comment by BrassLion** [comment]
@GoodluckH Has this PR been outdated by #33? If so, we should close this PR without merging.

**Comment by owlot** [comment]
> @GoodluckH Has this PR been outdated by #33? If so, we should close this PR without merging.

I've merged #33 into this branch, so it's not outdated. This is still the branch we want to merge to main

**Comment by GoodluckH** [comment]
@owlot @BrassLion Is there anyway we can test this on our end to review?

**Review by BrassLion — APPROVED** [review]
@GoodluckH Not sure how to best test this, I'll leave that up to @owlot's expertise.

Otherwise, I'm happy for this to get merged once it's sufficiently tested.

**Comment by GoodluckH** [comment]
OK, I will merge this PR since it's not a mission-critical feature. If there're problems down the road, we can always open tickets.

@owlot Thanks again for the help!

**Pull request merged**
